# Generated by Django 4.2.3 on 2023-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='design',
            new_name='designs',
        ),
    ]
