# Generated by Django 4.2.3 on 2023-07-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_design_designs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='designs',
            new_name='design',
        ),
    ]
