DROP TABLE IF EXISTS data_table;
CREATE TABLE IF NOT EXISTS data_table
(id INTEGER NOT NULL PRIMARY KEY,
`connection` VARCHAR(50),country VARCHAR(50),
app VARCHAR(50),platform VARCHAR(50),
date DATETIME,
ad_cpm DECIMAL(10,5),
install_rate DECIMAL(10,5),
iap_revenue DECIMAL(10,5),
ad_revenue DECIMAL(10,5),
spent DECIMAL(10,5),
fill_rate DECIMAL(10,5),
ctr DECIMAL(10,5),
unfilled_impressions DECIMAL(10,5),
downloads DECIMAL(10,5),
updates DECIMAL(10,5),
`returns` DECIMAL(10,5),
hits DECIMAL(10,5),
user_sessions DECIMAL(10,5),
new_users DECIMAL(10,5),
dau DECIMAL(10,5),
mau DECIMAL(10,5),
requests DECIMAL(10,5),
paying_users DECIMAL(10,5),
acq_requests DECIMAL(10,5),
acq_impressions DECIMAL(10,5),
acq_clicks DECIMAL(10,5),
acq_completions DECIMAL(10,5),
acq_installs DECIMAL(10,5),
impressions DECIMAL(10,5),
clicks DECIMAL(10,5),
completions DECIMAL(10,5),
conversions DECIMAL(10,5),
measurable_impressions DECIMAL(10,5),
viewable_impressions DECIMAL(10,5),
page_views DECIMAL(10,5),
iap_revenue_gross DECIMAL(10,5)
);